Do you want to build?
build aborted
Do you want to build?
build aborted
Do you want to build?
build aborted
Do you want to build?
build aborted
False
Do you want to build?
build aborted
False
Do you want to build?
build aborted
False
Do you want to build?
build aborted
/home/emilio/Documents/git/mehemken.io/app/~/Documents/git/mehemken.io/build/foo.txt
Do you want to build?
build aborted
/home/emilio/Documents/git/mehemken.io/app/~/Documents/git/mehemken.io/build
Do you want to build?
/home/emilio/Documents/git/mehemken.io/build
/home/emilio/Documents/git/mehemken.io/build
/home/emilio/Documents/git/mehemken.io/build
/home/emilio/Documents/git/mehemken.io/build
/home/emilio/Documents/git/mehemken.io/build
../build/
Do you want to build?
../build/
Do you want to build?
build aborted
../build/
../build/
Do you want to build?
There was an exception during the freeze.
Traceback (most recent call last):
  File "/home/emilio/bin/mehio", line 64, in <module>
    freezer.freeze()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 286, in _build_one
    % (response.status, url))
ValueError: Unexpected status '404 NOT FOUND' on URL /about/
Do you want to build?
There was an exception during the freeze.
Traceback (most recent call last):
  File "/home/emilio/bin/mehio", line 64, in <module>
    freezer.freeze()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 286, in _build_one
    % (response.status, url))
ValueError: Unexpected status '404 NOT FOUND' on URL /about/
Do you want to build?
There was an exception during the freeze.
Traceback (most recent call last):
  File "/home/emilio/bin/mehio", line 64, in <module>
    freezer.freeze()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 286, in _build_one
    % (response.status, url))
ValueError: Unexpected status '404 NOT FOUND' on URL /about
../build/
Do you want to build?
There was an exception during the freeze.
Traceback (most recent call last):
  File "./app.py", line 63, in <module>
    freezer.freeze()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 323, in _build_one
    with open(filename, 'wb') as fd:
IsADirectoryError: [Errno 21] Is a directory: '/home/emilio/Documents/git/mehemken.io/app/../build/about'
Do you want to build?
Do you want to build?
Do you want to build?
build aborted
Do you want to build?
There was an exception during the freeze.
Traceback (most recent call last):
  File "./app.py", line 62, in <module>
    freezer.freeze()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 157, in freeze
    new_filename = self._build_one(url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask_frozen/__init__.py", line 268, in _build_one
    base_url=base_url)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/testing.py", line 127, in open
    follow_redirects=follow_redirects)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 45, in about
    return render_template('about.html', page=page)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/emilio/Documents/git/mehemken.io/app/templates/about.html", line 1, in top-level template code
    {% extends 'layout.html' %}
  File "/home/emilio/Documents/git/mehemken.io/app/templates/layout.html", line 34, in top-level template code
    <a class="navbar-brand" href="{{ url_for(index) }}">mehemken.io</a>
  File "/home/emilio/anaconda3/envs/frozen-flask/lib/python3.6/site-packages/flask/helpers.py", line 280, in url_for
    if endpoint[:1] == '.':
jinja2.exceptions.UndefinedError: 'index' is undefined
Do you want to build?
Do you want to build?
